export const styles = `
p,li { overflow-wrap:anywhere; }
:host { display:block; min-height:100%; background:var(--primary-background-color,#f4f5f8); color:var(--primary-text-color,#202c37); font:15px/1.5 system-ui,sans-serif; }
* { box-sizing:border-box; } main { max-width:1200px; margin:auto; padding:24px; } h1 { margin:0; font-size:28px; } h2 { font-size:21px; margin:0 0 12px; } h3 { font-size:17px; } p { margin:8px 0; } small,.hint { color:var(--secondary-text-color,#596773); } code { overflow-wrap:anywhere; }
header { display:flex; align-items:center; justify-content:space-between; gap:16px; flex-wrap:wrap; } nav,.row,.resource-nav,.toolbar { display:flex; align-items:center; gap:8px; flex-wrap:wrap; } nav { margin:18px 0; } nav button[aria-current="page"] { background:var(--primary-color,#167b94); color:white; }
section { background:var(--card-background-color,#fff); border:1px solid var(--divider-color,#d5dce3); border-radius:12px; padding:20px; margin:16px 0; min-width:0; } section section { border-radius:8px; } article { border-top:1px solid var(--divider-color,#d5dce3); padding:12px 0; } details { padding:12px 0; } summary { cursor:pointer; font-weight:600; }
button,input,select,textarea { font:inherit; color:inherit; } button { background:var(--card-background-color,#fff); border:1px solid var(--divider-color,#bdc9d2); padding:8px 14px; border-radius:8px; cursor:pointer; min-height:42px; } button.primary { background:var(--primary-color,#167b94); color:white; } button:disabled { opacity:.5; cursor:default; } button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible,summary:focus-visible,a:focus-visible,[tabindex]:focus-visible { outline:3px solid var(--primary-color,#167b94); outline-offset:2px; }
.field { display:flex; flex-direction:column; gap:5px; margin:12px 0; max-width:700px; } label { font-weight:500; } input:not([type=checkbox]),select,textarea { border:1px solid var(--divider-color,#bdc9d2); border-radius:6px; background:var(--card-background-color,#fff); padding:9px; min-width:0; max-width:100%; } .field input,.field select,.field textarea { width:100%; } textarea { resize:vertical; } .field textarea { font:14px/1.5 ui-monospace,monospace; } input[type=checkbox] { width:20px; height:20px; vertical-align:middle; } fieldset { border:1px solid var(--divider-color,#d5dce3); border-radius:8px; margin:12px 0; min-width:0; } legend { padding:0 6px; font-weight:600; } .check { display:inline-flex; gap:5px; margin:8px; align-items:center; } .checks { display:flex; gap:12px; flex-wrap:wrap; }
.banner { padding:12px 16px; border-radius:8px; background:var(--secondary-background-color,#e3eef2); margin:12px 0; overflow-wrap:anywhere; } .error,[aria-invalid=true] { color:var(--error-color,#b3261e); } [aria-invalid=true] { border-color:var(--error-color,#b3261e); } [hidden] { display:none!important; } dl { display:grid; grid-template-columns:minmax(140px,1fr) 3fr; gap:8px 20px; } dt { color:var(--secondary-text-color,#596773); } dd { margin:0; overflow-wrap:anywhere; } .badge { padding:6px 12px; background:var(--secondary-background-color,#e3eef2); border-radius:20px; }
.toolbar { position:sticky; top:0; padding:12px 0; background:var(--primary-background-color,#f4f5f8); z-index:2; } pre { white-space:pre-wrap; overflow-wrap:anywhere; font:13px/1.5 ui-monospace,monospace; } .table-wrap { overflow:auto; } table { width:100%; border-collapse:collapse; font-size:13px; } th,td { padding:9px; text-align:left; border-bottom:1px solid var(--divider-color,#d5dce3); max-width:300px; overflow-wrap:anywhere; } th { white-space:nowrap; } progress { width:min(350px,100%); accent-color:var(--primary-color,#167b94); }
.timeline { margin:18px 0; padding-top:42px; overflow:hidden; position:relative; } .ruler { position:absolute; top:0; left:160px; right:12px; height:40px; font-size:10px; } .ruler span { position:absolute; width:100px; transform:translateX(-50%); } .ruler span:first-child { transform:none; } .ruler span:last-child { transform:translateX(-100%); } .lane { display:flex; min-height:36px; align-items:center; } .lane-label { width:150px; flex-shrink:0; overflow-wrap:anywhere; padding-right:8px; font-size:12px; } .track { position:relative; width:100%; min-width:0; height:32px; margin:0 12px 0 10px; background:var(--secondary-background-color,#f1f4f6); border-radius:4px; } .bar { position:absolute; top:7px; height:18px; min-width:3px; border-radius:3px; background:#4f8a96; } .bar.activity { background:#7762a6; } .bar.active { top:12px; height:8px; background:#168555; } .bar.ramp { background:linear-gradient(90deg,#f2d69b,#b88a2e); } .marker { position:absolute; top:3px; transform:translateX(-50%); color:var(--primary-color,#167b94); }
@media (max-width:600px) { main { padding:14px; } section { padding:14px; } nav { gap:5px; } nav button { padding:7px 10px; } dl { grid-template-columns:1fr; gap:3px; } dd { margin-bottom:8px; } .lane-label { width:90px; font-size:11px; } .ruler { left:100px; } .ruler span { width:60px; } .row input { width:100%; } }
`;
